task: detection

use_wandb : True

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# num_classes: 365
# remap_mscoco_category: False

# num_classes: 91
# remap_mscoco_category: False

num_classes: 80
remap_mscoco_category: False


train_dataloader: 
  total_batch_size: 64
  # batch_size: 8  # ← set your desired batch size here
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /dataset/images_rgb_train/
    ann_file: /dataset/images_rgb_train/merged_coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  # num_workers: 0
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFuncion


val_dataloader:
  # batch_size: 8  # ← set your desired batch size here
  total_batch_size: 64
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /dataset/images_thermal_val/
    # ann_file: /dataset/images_thermal_val/coco.json
    ann_file: /dataset/images_thermal_val/merged_coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 4
  # num_workers: 0
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
